/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemahospital;


import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.api.tree.BreakTree;

/**
 *
 * @author gonza
 */
public class PantallaConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaConsulta
     */
    Connection con; 
    
    public PantallaConsulta() {
       
        initComponents();
        
        
       
        try {
           
            Class.forName("com.mysql.jdbc.Driver"); // SE FIJA SI ESTA LA LIBRERIA CORRESPONDIENTE
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDocumentoBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfApellidoBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPacientes = new javax.swing.JTable();
        jbBuscar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sistemahospital/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("PantallaConsulta.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("PantallaConsulta.jLabel2.text")); // NOI18N

        tfDocumentoBusqueda.setText(bundle.getString("PantallaConsulta.tfDocumentoBusqueda.text")); // NOI18N
        tfDocumentoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDocumentoBusquedaActionPerformed(evt);
            }
        });

        jLabel3.setText(bundle.getString("PantallaConsulta.jLabel3.text")); // NOI18N

        tfApellidoBusqueda.setText(bundle.getString("PantallaConsulta.tfApellidoBusqueda.text")); // NOI18N
        tfApellidoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoBusquedaActionPerformed(evt);
            }
        });

        jtPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "documento", "nombre", "apellido", "sexo", "fecha nac"
            }
        ));
        jtPacientes.setName(""); // NOI18N
        jScrollPane1.setViewportView(jtPacientes);

        jbBuscar.setText(bundle.getString("PantallaConsulta.jbBuscar.text")); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfDocumentoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(tfApellidoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jbBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDocumentoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellidoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDocumentoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDocumentoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDocumentoBusquedaActionPerformed

    private void tfApellidoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoBusquedaActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        
        
        DefaultTableModel modelo = (DefaultTableModel) jtPacientes.getModel();// crea la tabla en la variable Jtabla
        modelo.setColumnCount(5); 
        modelo.setRowCount(0); // LIMPIA LAS FILAS PARA LA PROXIMA BSQUEDA
        try {
            
             
            con = DriverManager.getConnection("jdbc:mysql://localhost/SistemaHospital","root","");
            Statement stmt = con.createStatement();
            
           
            if (((tfDocumentoBusqueda.getText().isEmpty())) && ((tfApellidoBusqueda.getText().isEmpty()))){ // MUESTRA DE TODOS LOS REGISTROS
                         
                ResultSet rs = stmt.executeQuery("SELECT * FROM pacientes");//WHERE documento ="+tfDocumentoBusqueda.getText())";
            
                 while (rs.next()){
            
                    String[] fila = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};   
                    modelo.addRow(fila);
                    
                }
               
            }
         
            
            if ((tfDocumentoBusqueda.getText().length() > 0) && ((tfApellidoBusqueda.getText().isEmpty()))){ // BUSQUEDA POR DOCUMENTO
            
                ResultSet rs = stmt.executeQuery("SELECT * FROM pacientes WHERE documento ="+tfDocumentoBusqueda.getText());
            
                while (rs.next()){
            
                    String[] fila = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};   
                    modelo.addRow(fila);
            
                }
            }
            
            if ((tfDocumentoBusqueda.getText().isEmpty()) && ((tfApellidoBusqueda.getText().length() > 0))){ // BUSQUEDA POR APPELLIDO
            
                ResultSet rs = stmt.executeQuery("SELECT * FROM pacientes WHERE apellido = '"+tfApellidoBusqueda.getText()+"'");
            
                while (rs.next()){
            
                    String[] fila = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};   
                    modelo.addRow(fila);
            
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PantallaConsulta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "no se puede conectar a la base de datos");
        }
       
       
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JTable jtPacientes;
    private javax.swing.JTextField tfApellidoBusqueda;
    private javax.swing.JTextField tfDocumentoBusqueda;
    // End of variables declaration//GEN-END:variables
}
