/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;


/**
 *
 * @author gonza
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
   
    
    public Principal() {
        initComponents();
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuPaciente = new javax.swing.JMenu();
        jMenuRegistrar = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vista/Bundle"); // NOI18N
        jMenuItem1.setText(bundle.getString("Principal.jMenuItem1.text")); // NOI18N

        jMenuItem4.setText(bundle.getString("Principal.jMenuItem4.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArchivo.setText(bundle.getString("Principal.jMenuArchivo.text")); // NOI18N

        jMenuItem2.setText(bundle.getString("Principal.jMenuItem2.text")); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem2);

        jMenuBar1.add(jMenuArchivo);

        jMenuPaciente.setText(bundle.getString("Principal.jMenuPaciente.text")); // NOI18N

        jMenuRegistrar.setText(bundle.getString("Principal.jMenuRegistrar.text")); // NOI18N
        jMenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuRegistrar);

        jMenuConsulta.setText(bundle.getString("Principal.jMenuConsulta.text")); // NOI18N
        jMenuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuConsulta);

        jMenuBar1.add(jMenuPaciente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaActionPerformed
       
                                           
    }//GEN-LAST:event_jMenuConsultaActionPerformed

    private void jMenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarActionPerformed
    
    }//GEN-LAST:event_jMenuRegistrarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuConsulta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenu jMenuPaciente;
    public javax.swing.JMenuItem jMenuRegistrar;
    // End of variables declaration//GEN-END:variables
}
